spring.application.name=vet

spring.datasource.url=jdbc:postgresql://localhost:5432/vet_db
spring.datasource.username=admin
spring.datasource.password=Abc123*

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.springframework.security.web.=debug